#pragma once
enum E_MONSTER_ANIMATION_TYPE {
	E_IDLE, E_WALK, E_RUN, E_DASH, E_ATTACK, E_HIT, E_DEATH
};

enum E_PLAYER_ANIMATION_TYPE {
	E_IDLE, E_WALK, E_RUN, E_DASH, E_JUMP, E_TIRED,
	E_ATTACK0, E_ATTACK1, E_ATTACK2, E_ATTACK3, E_ATTACK4,
	E_DAMAGE,
	E_DIE0, E_DIE1, E_DIE2,
	VICTORY1, VICTORY2
};