#pragma once
enum class E_MONSTER_STATE {
	E_WANDER, E_TRACK, E_IDLE
};

enum E_MONSTER_ANIMATION_TYPE {
	E_M_IDLE, E_M_WALK, E_M_RUN, E_M_DASH, E_M_ATTACK, E_M_HIT, E_M_DEATH
};

enum class E_BOSS_STATE {
	E_B_WANDER, E_B_TRACK, E_B_IDLE, E_B_SKILL
};

enum E_BOSS_ANIMATION_TYPE {
	E_B_IDLE,E_B_WALK, E_B_RUN, E_B_DASH, E_B_ATTACK,E_B_HIT,E_B_DEATH,E_B_ROAR,E_B_JUMPATTACK,E_B_TORNADO,E_B_DEFENCE,E_B_SUMMON
};

enum E_PLAYER_ANIMATION_TYPE {
	E_IDLE, E_WALK, E_RUN, E_DASH, E_JUMP, E_TIRED,
	E_ATTACK0, E_ATTACK1, E_ATTACK2, E_ATTACK3, E_ATTACK4,
	E_DAMAGE,
	E_DIE0, E_DIE1, E_DIE2,
	VICTORY1, VICTORY2
	,E_SKILL
};